import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget/generated/GeneratedSuperiorWidget2.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget/generated/GeneratedUbicaaquitusaloncorrespondienteWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget/generated/GeneratedLaescuelaconstadevariasaulaslascualessepresentanacontin.dart';

/* Frame Aulas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAulasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 137.0,
                child: GeneratedSuperiorWidget2(),
              ),
              Positioned(
                left: 22.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 73.0,
                child: GeneratedUbicaaquitusaloncorrespondienteWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 300.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 100.0,
                child:
                    GeneratedLaescuelaconstadevariasaulaslascualessepresentanacontin(),
              ),
              Positioned(
                left: 55.999267578125,
                top: 797.0,
                right: null,
                bottom: null,
                width: 315.0015869140625,
                height: 41.0,
                child: GeneratedGroup3Widget(),
              )
            ]),
      ),
    ));
  }
}
