import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedprincipalwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedprincipalwidget/generated/GeneratedBotonesWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedprincipalwidget/generated/GeneratedBotonesWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedprincipalwidget/generated/GeneratedBotonesWidget3.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedprincipalwidget/generated/GeneratedBotonesWidget2.dart';

/* Frame Principal
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPrincipalWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 268.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedBotonesWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedBotonesWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedBotonesWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 90.0,
                child: GeneratedBotonesWidget3(),
              )
            ]),
      ),
    ));
  }
}
