import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedSuperiorWidget7.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget2.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget4.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget5.dart';
import 'package:flutterapp/proyecto_20finalapp/generatediphone11promax1widget/generated/GeneratedPerfilesWidget3.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 137.0,
                child: GeneratedSuperiorWidget7(),
              ),
              Positioned(
                left: 19.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget2(),
              ),
              Positioned(
                left: 19.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget3(),
              ),
              Positioned(
                left: 34.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget4(),
              ),
              Positioned(
                left: 19.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 93.0,
                child: GeneratedPerfilesWidget5(),
              )
            ]),
      ),
    ));
  }
}
