import 'package:flutter/material.dart';

/* Frame arrow-forward-circle-sharp
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedArrowforwardcirclesharpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 59.0,
        height: 62.0,
      ),
    ));
  }
}
