import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedMaestraTaniaWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedDatosWidget2.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedDatosWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedSuperiorWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedPerfindemaestrosWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedmaestrosperfilwidget/generated/GeneratedDatosWidget.dart';

/* Frame Maestros Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaestrosPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 137.0,
                child: GeneratedSuperiorWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 163.0,
                height: 204.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 59.0,
                child: GeneratedPerfindemaestrosWidget(),
              ),
              Positioned(
                left: 195.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 39.0,
                child: GeneratedMaestraTaniaWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 350.0014343261719,
                height: 84.0,
                child: GeneratedDatosWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 350.0014343261719,
                height: 84.0,
                child: GeneratedDatosWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 350.0014343261719,
                height: 84.0,
                child: GeneratedDatosWidget2(),
              ),
              Positioned(
                left: 80.0,
                top: 807.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 50.0,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
