import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedUbicaaquitusaloncorrespondienteWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedSuperiorWidget3.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedSEDESCARGARAELMAPAESCOLARWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedLaescuelaconstadevariasaulaslascualessepresentanacontin1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedaulaswidget1/generated/GeneratedGroup5Widget.dart';

/* Frame Aulas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAulasWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 137.0,
                child: GeneratedSuperiorWidget3(),
              ),
              Positioned(
                left: 22.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 73.0,
                child: GeneratedUbicaaquitusaloncorrespondienteWidget1(),
              ),
              Positioned(
                left: 27.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 300.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 97.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 100.0,
                child:
                    GeneratedLaescuelaconstadevariasaulaslascualessepresentanacontin1(),
              ),
              Positioned(
                left: 55.999267578125,
                top: 797.0,
                right: null,
                bottom: null,
                width: 315.0015869140625,
                height: 41.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 14.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 145.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 60.0,
                child: GeneratedSEDESCARGARAELMAPAESCOLARWidget(),
              ),
              Positioned(
                left: 181.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 33.000003814697266,
                height: 25.000001907348633,
                child: GeneratedGroup5Widget(),
              )
            ]),
      ),
    ));
  }
}
