import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedBienvenidoaelmundodelalecturaWidget1.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedSuperiorWidget5.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedHAZINICIADOSESIONCORRECTAMENTEWidget.dart';
import 'package:flutterapp/proyecto_20finalapp/generatedbibliotecawidget1/generated/GeneratedRectangle15Widget.dart';

/* Frame Biblioteca
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBibliotecaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 137.0,
                child: GeneratedSuperiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.07653985507246377;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 31.6875;

                  double percentHeight = 0.0380859375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 34.125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * -2.082955917874396,
                        translateY: constraints.maxHeight * 1.12158203125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget12())
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 202.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 82.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 174.0,
                child: GeneratedBienvenidoaelmundodelalecturaWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 340.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 71.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 134.0,
                child: GeneratedHAZINICIADOSESIONCORRECTAMENTEWidget(),
              ),
              Positioned(
                left: 146.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 101.0,
                child: GeneratedGroup4Widget(),
              )
            ]),
      ),
    ));
  }
}
